info:
  project:
    name: Spring Start
    version: 0.3.1
  # remember to update static/install.sh as well:
  spring-boot:
    version: 1.2.5.RELEASE
endpoints:
  env:
    keysToSanitize: key,secret,password,VCAP_SERVICES

initializr:
  groupId:
    value: com.sankuai.meituan.waimai
  artifactId:
    value: demo
  version:
    value: 0.0.1-SNAPSHOT
  name:
    value: Demo
  description:
    value: Demo project for Spring Boot
  packageName:
    value: com.sankuai.meituan.waimai.demo
  env:
    artifactRepository: https://repo.spring.io/lib-release
    boms:
      vaadin-bom:
        groupId: com.vaadin
        artifactId: vaadin-bom
        version: 7.4.5
      cloud-bom:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-starter-parent
        mappings:
          - versionRange: "[1.2.3.RELEASE,1.3.0.M1)"
            version: Angel.SR3
          - versionRange: 1.3.0.M1
            version: Brixton.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
  dependencies:
    - name: 项目模板
      content:
        - name: 服务化Server基础模板
          id: rpc-server
          description: 提供一个基础的服务化模板支持
          groupId: org.springframework.boot
          artifactId: spring-boot-starter
        - name: 服务化Client基础模板
          id: rpc-client
          description: 提供一个基础的服务化模板支持
        - name: Web基础模板
          id: web
          description: Support for full-stack web development, including Tomcat and spring-webmvc
          facets:
            - web
    - name: 基础组件
      content:
        - name: Log4j2
          id: log4j2
          description: 提供log4j2支持
        - name: Thrift
          id: thrift
          description: 提供thrift支持
          facets:
            - thrift
    - name: Web模板引擎
      content:
        - name: Freemarker
          id: freemarker
          description: Support for the FreeMarker templating engine
          facets:
            - web
        - name: Mustache
          id: mustache
          description: Support for the Mustache templating engine
          versionRange: 1.2.2.RELEASE
          facets:
            - web
        - name: Websocket
          id: websocket
          description: Support for websocket development with Tomcat
    - name: 工具依赖
      content:
        - name: Guava
          id: guava
          description: Support for Guava
    - name: 第三方依赖
      content:
        - name: JDBC
          id: jdbc
          description: Support for JDBC databases
        - name: JPA
          id: data-jpa
          description: Support for the Java Persistence API including spring-data-jpa, spring-orm and Hibernate
          aliases:
            - jpa
        - name: MongoDB
          id: data-mongodb
          description: Support for the MongoDB NoSQL Database, including spring-data-mongodb
        - name: Redis
          id: redis
          description: Support for the REDIS key-value data store, including spring-redis
    - name: Database
      content:
        - name: H2
          id: h2
          description: Support for the H2 database (with embedded support)
          groupId: com.h2database
          artifactId: h2
          scope: runtime
        - name: HSQLDB
          id: hsql
          description: Support for the HSQLDB database (with embedded support)
          groupId: org.hsqldb
          artifactId: hsqldb
          scope: runtime
        - name: MySQL
          id: mysql
          description: Support for the MySQL jdbc driver
          groupId: mysql
          artifactId: mysql-connector-java
          scope: runtime
    - name: I/O
      content:
        - name: AMQP
          id: amqp
          description: Support for the Advanced Message Queuing Protocol via spring-rabbit
  types:
    - name: Maven POM
      id: maven-build
      description: Generate a Maven pom.xml
      sts-id: pom.xml
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      sts-id: starter.zip
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Gradle Config
      id: gradle-build
      description: Generate a Gradle build file
      sts-id: build.gradle
      tags:
        build: gradle
        format: build
      default: false
      action: /build.gradle
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      sts-id: gradle.zip
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  javaVersions:
    - id: 1.6
      default: false
    - id: 1.7
      default: true
    - id: 1.8
      default: false
  languages:
    - name: Groovy
      id: groovy
      default: false
    - name: Java
      id: java
      default: true
  bootVersions:
    - name : Latest SNAPSHOT
      id: 1.2.4.BUILD-SNAPSHOT
      default: false
    - name: 1.2.3
      id: 1.2.3.RELEASE
      default: true
    - name: 1.1.12
      id: 1.1.12.RELEASE
      default: false